// <auto-generated />
namespace FormulaIFS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnovaTabela_Participacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnovaTabela_Participacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201809210214158_addnovaTabela_Participacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
